### ISSUE TITLE
Migrations and seeders

### ISSUE THREAD

**Issue by MatteoTarabella04** [MatteoTarabella04/BoolBnB#1]
Tasks: for (boolbnb_db)
- Create tables (ER Base)
- Modify user table and model
- Migrate
- Add seeder *
- Seed all
- Check result on phpMyAdmin

**Comment by mattiavolpe** [comment]
- Modified users default migration
- Modified User default model
- Modified User default validation
- Modified RegisteredUserController default structure
- Modified (just for compatibility) dashboard and profile views
- Made migrations
